// <auto-generated />
using System;
using G6.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace G6.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240329002755_CriacaoDoBanco")]
    partial class CriacaoDoBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Ativos")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("G6.Domain.Entities.Ativos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<decimal?>("averageDailyVolume10Day")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("averageDailyVolume3Month")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("longName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ativos", "Ativos");
                });

            modelBuilder.Entity("G6.Domain.Entities.DadosHistoricosAtivos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AdjustedClose")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("AtivosId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Close")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("High")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Low")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Open")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("Volume")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtivosId");

                    b.ToTable("DadosHistoricosAtivos", "Ativos");
                });

            modelBuilder.Entity("G6.Domain.Entities.DadosHistoricosAtivos", b =>
                {
                    b.HasOne("G6.Domain.Entities.Ativos", "Ativos")
                        .WithMany("DadosHistoricosAtivos")
                        .HasForeignKey("AtivosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ativos");
                });

            modelBuilder.Entity("G6.Domain.Entities.Ativos", b =>
                {
                    b.Navigation("DadosHistoricosAtivos");
                });
#pragma warning restore 612, 618
        }
    }
}
