name: Andre Actions
run-name: ${{ github.actor }} GitHub Actions 
on:
  push:
    branches:
      - 'master'
jobs:
  GitHub-Actions:
    runs-on: self-hosted
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: '/actions-runner/_work/G6/G6'
      - name: Setup envs
        run: |
          cd /actions-runner/_work/G6/G6
          git pull origin master
      - name: Build project
        run: |
          cd /actions-runner/_work/G6/G6
          dotnet build
      - name: Run project
        run: |
          cd /actions-runner/_work/G6/G6
          dotnet run
