name: Andre Actions
run-name: ${{ github.actor }} GitHub Actions 
on:
  push:
    branches:
      - 'master'
jobs:
  GitHub-Actions:
    runs-on: self-hosted
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          path: '/home/Repo/'
      - name: Setup envs
        run: |
          cd /home/Repo/G6
          git pull origin master

